stages:
  - docker
  - requirements

# Uses Git commit hash as tag
variables:
  IMAGE_NAME: skyvault
  TAG: $CI_COMMIT_SHORT_SHA 


#Creating docker
build-docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$TAG .


#Installing Requirements
build-requirements:
  stage: requirements
  image: python:latest
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
