version: '3.8'

services:
  skyvault:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-this
    volumes:
      - ./uploads:/app/uploads
      - ./encrypted_files:/app/encrypted_files
    restart: unless-stopped